dist:
  jammy
git:
  depth: 3
branches:
  except:
  - docs
language: node_js
npm_args: "--version"
node_js:
  - 18
script:
  - npm install --legacy-peer-deps && cd demo && npm install && cd -
  - npm run lint
  - npm run build
  - npm test
